#pragma once
#define EDITOR_NAME "Map Editor"
#define EDITOR_VERSION_NUMBER "0.8"
#define EDITOR_VERSION EDITOR_VERSION_NUMBER"-alpha"
#define BUILD_NUMBER "20220306"
#define EDITOR_TITLE EDITOR_NAME " v" EDITOR_VERSION_NUMBER
