#pragma once
#define EDITOR_NAME "Map Editor"
#define EDITOR_VERSION_NUMBER "0.1"
#define EDITOR_VERSION EDITOR_VERSION_NUMBER"-alpha"
#define BUILD_NUMBER "20210908"
#define EDITOR_TITLE EDITOR_NAME " v" EDITOR_VERSION_NUMBER
